page 50102 "PVS Copilot Case Dialog"
{
    PageType = PromptDialog;
    Caption = 'New Case with Copilot';
    ApplicationArea = All;
    IsPreview = true;
    PromptMode = Prompt;

    layout
    {
        area(Prompt)
        {
            field(UserPromptField; UserPromptTxt)
            {
                ApplicationArea = All;
                Caption = 'Describe the new case';
                MultiLine = true;
                InstructionalText = 'Describe the print job you need to quote — for example: "4-page brochure, 5000 copies, coated paper, customer segment EXPORT, needed within 2 weeks".';
            }
        }
        area(Content)
        {
            group(ProposedCaseGroup)
            {
                Caption = 'Proposed Case Details';
                InstructionalText = 'Review and adjust the values proposed by Copilot before creating the case.';

                field(ProposedJobTypeField; ProposedJobTypeCode)
                {
                    ApplicationArea = All;
                    Caption = 'Job Type';
                    ToolTip = 'Proposed job type code based on historical patterns.';
                }
                field(ProposedCustomerNoField; ProposedCustomerNo)
                {
                    ApplicationArea = All;
                    Caption = 'Customer No.';
                    ToolTip = 'Proposed customer number (if the description included a customer reference).';
                }
                field(ProposedDescriptionField; ProposedDescription)
                {
                    ApplicationArea = All;
                    Caption = 'Description';
                    MultiLine = true;
                    ToolTip = 'Proposed case description generated by Copilot.';
                }
                field(ProposedQuantityField; ProposedQuantity)
                {
                    ApplicationArea = All;
                    Caption = 'Quantity';
                    ToolTip = 'Proposed order quantity.';
                }
                field(ProposedMaterialCodeField; ProposedMaterialCode)
                {
                    ApplicationArea = All;
                    Caption = 'Material Code';
                    ToolTip = 'Proposed primary material code.';
                }
                field(ProposedTurnaroundDaysField; ProposedTurnaroundDays)
                {
                    ApplicationArea = All;
                    Caption = 'Turnaround Days';
                    ToolTip = 'Proposed number of production days.';
                }
                field(ProposedTotalAmountField; ProposedTotalAmount)
                {
                    ApplicationArea = All;
                    Caption = 'Estimated Amount';
                    ToolTip = 'Estimated total sales amount based on historical patterns.';
                }
            }
        }
    }

    actions
    {
        area(SystemActions)
        {
            systemaction(Generate)
            {
                Caption = 'Generate';
                ToolTip = 'Generate a case suggestion based on your description and historical patterns.';

                trigger OnAction()
                begin
                    RunGeneration();
                end;
            }
            systemaction(Regenerate)
            {
                Caption = 'Regenerate';
                ToolTip = 'Request a new suggestion from Copilot.';

                trigger OnAction()
                begin
                    RunGeneration();
                end;
            }
            systemaction(OK)
            {
                Caption = 'Create Case';
                ToolTip = 'Accept the suggestion and create the new PrintVis case.';
            }
            systemaction(Cancel)
            {
                Caption = 'Discard';
                ToolTip = 'Close the dialog without creating a case.';
            }
        }
    }

    trigger OnQueryClosePage(CloseAction: Action): Boolean
    begin
        if CloseAction = Action::OK then
            if not HasGenerated then
                Error('Please use the Generate action to get a suggestion before creating a case.');
        exit(true);
    end;

    /// <summary>
    /// Returns the suggested case field values to the caller after the dialog is accepted.
    /// </summary>
    procedure GetSuggestedValues(
        var JobTypeCode: Code[20];
        var CustomerNo: Code[20];
        var Description: Text[200];
        var MaterialCode: Code[20];
        var Quantity: Decimal;
        var TurnaroundDays: Integer)
    begin
        JobTypeCode := ProposedJobTypeCode;
        CustomerNo := ProposedCustomerNo;
        Description := ProposedDescription;
        MaterialCode := ProposedMaterialCode;
        Quantity := ProposedQuantity;
        TurnaroundDays := ProposedTurnaroundDays;
    end;

    local procedure RunGeneration()
    var
        CopilotCaseGen: Codeunit "PVS Copilot Case Gen";
        SuggestedCase: Record "PVS Case History" temporary;
    begin
        if UserPromptTxt = '' then
            Error('Please enter a description for the new case before generating.');

        CopilotCaseGen.GenerateCaseSuggestion(UserPromptTxt, SuggestedCase);

        ProposedJobTypeCode := SuggestedCase."Job Type Code";
        ProposedCustomerNo := SuggestedCase."Customer No.";
        ProposedDescription := SuggestedCase.Description;
        ProposedMaterialCode := SuggestedCase."Material Code";
        ProposedQuantity := SuggestedCase.Quantity;
        ProposedTurnaroundDays := SuggestedCase."Turnaround Days";
        ProposedTotalAmount := SuggestedCase."Total Amount";
        HasGenerated := true;

        CurrPage.PromptMode := PromptMode::Content;
        CurrPage.Update(false);
    end;

    var
        UserPromptTxt: Text;
        ProposedJobTypeCode: Code[20];
        ProposedCustomerNo: Code[20];
        ProposedDescription: Text[200];
        ProposedMaterialCode: Code[20];
        ProposedQuantity: Decimal;
        ProposedTurnaroundDays: Integer;
        ProposedTotalAmount: Decimal;
        HasGenerated: Boolean;
}
